// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Search with pagefind', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Search with pagefind', async function() {
    // Test name: Search with pagefind
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://perplex.desider.at/")
    // 2 | setWindowSize | 3072x1701 | 
    await driver.manage().window().setRect({ width: 3072, height: 1701 })
    // 3 | click | css=#search path | 
    await driver.findElement(By.css("#search path")).click()
    // 4 | click | css=.pagefind-ui__search-input | 
    await driver.findElement(By.css(".pagefind-ui__search-input")).click()
    // 5 | type | css=.pagefind-ui__search-input | Emphasis
    await driver.findElement(By.css(".pagefind-ui__search-input")).sendKeys("Emphasis")
    // 6 | click | linkText=Emphasis | 
    await driver.findElement(By.linkText("Emphasis")).click()
  })
})
