# Line length should not be limited, because we use soft wrapping
MD013: false  
# Empty lines above and below headings
MD022:
  lines_above: 1
  lines_below: 0
# Duplicate headings
MD024: 
  siblings_only: true
# Ordered list
MD029: 
  style: "ordered"
# Blank lines around lists aren’t necessary for Goldmark
MD032: false
# No inline HTML. But because inline HTML is already skipped and removed
# with our Hugo configuration, the rule is not necessary. 
# And it would also be triggered by angled brackets intended for the typographer.
MD033: false 
# Emphasis style
MD049:
  style: "underscore"
# Strong style
MD050:
  style: "asterisk"  
